Updates

diff --git a/capictl b/capictl
--- a/capictl
+++ b/capictl
@@ -186,6 +186,12 @@ fi
 if ! ${REUSE_CLUSTER_YAML}; then
     rm -f cluster.yaml
 fi
+if test -z HCLOUD_SSH_KEY; then
+    SSH_KEY_NAME=caph
+else
+    SSH_KEY_NAME="${HCLOUD_SSH_KEY}"
+fi
+export SSH_KEY_NAME
 if ! test -f cluster.yaml; then
     clusterctl generate cluster "${CLUSTER_NAME}" \
         --kubernetes-version="v${KUBERNETES_VERSION}" \
@@ -196,6 +202,9 @@ if ! test -f cluster.yaml; then
 fi
 if test -n "${IMAGE_NAME}"; then
     sed -i -E "s/^(\s+imageName:) .+$/\1 ${IMAGE_NAME}/" cluster.yaml
+else
+    echo "ERROR: IMAGE_NAME not set"
+    exit 1
 fi
 if test -n "${POD_CIDR}"; then
     export POD_CIDR
